version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      open-pull-requests-limit: 7
      schedule:
          interval: "daily"
      groups:
        playwright:
          patterns:
            - "@playwright/test"
            - "playwright-core"
        vitest:
          patterns:
            - "@vitest/coverage-v8"
            - "@vue/test-utils"
            - "vitest"
            - "@nuxt/test-utils"
